package com.encoder.zidingyi.faxiaoxi;

import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;

public class TimeClientHandler extends ChannelInboundHandlerAdapter{
	
	private int counter;
	private byte[] req;
	public TimeClientHandler()
	{
		req = ("asfdf").getBytes();
	}
	
	public void channelActive(ChannelHandlerContext ctx)
	{
		Msg msg=new Msg();
		msg.setNameLength("WangAHa".getBytes().length);
		msg.setName("WangAHa");
		msg.setAge(20);
		msg.setContentLength("WangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaa".length());
		msg.setContent("WangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdffasddddffffaAHafasdfgffafffffWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaaWangAHafasdfgasgsadfsafasdfffffffffassssssdddddffffffffffffaa");

		ctx.writeAndFlush(msg);//一发送就会进入编码器
	}
	
	public void channelRead(ChannelHandlerContext ctx,Object msg)throws Exception
	{

	}
	
	public void exceptionCaught(ChannelHandlerContext ctx,Throwable cause)
	{
		ctx.close();
	}
}
